</div>
<footer class="footer">
  <div class="container">
    <ul class="nav nav-pills">
         <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin">Admin Dashboard</a>
          </li>
          <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin/locations">Edit Locations</a>
          </li>
          <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin/initiatives">Edit Initiatives</a>
          </li>
          <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin/sessions">Sessions List</a>
          </li>
          <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin/jsonimport">Direct JSON Import</a>
          </li>
          <li class="">
            <a href="<?php echo $this->baseUrl(); ?>/admin/logout">Logout</a>
          </li>
    </ul>
    <div class="row-fluid">
      <div class="col-md-8">
        <p>Built with <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>.</p>
        <p>Code licensed under <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>, documentation under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        <p><a href="http://glyphicons.com">Glyphicons Free</a> licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
</footer>