</div> <!-- Close #container - located in header.phtml -->
<footer class="footer">
  <div class="container" id="footer-content">
    <ul class="nav nav-pills">
      <li class="">
        <a href="/sumaserver/admin">Dashboard</a>
      </li>
      <li class="">
        <a href="/sumaserver/admin/locations">Locations</a>
      </li>
      <li class="">
        <a href="/sumaserver/admin/initiatives">Initiatives</a>
      </li>
      <li class="">
        <a href="/sumaserver/admin/sessions">Sessions</a>
      </li>
      <li class="">
        <a href="/sumaserver/admin/jsonimport">JSON Import</a>
      </li>
      <li class="">
        <a href="/sumaserver/admin/logout">Logout</a>
      </li>
    </ul>
  </div>
  <div class="container" id="footer-postcontent">
    <p>Built with <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>.</p>
    <p>Code licensed under <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>, documentation under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
    <p><a href="http://glyphicons.com">Glyphicons Free</a> licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
  </div>
</footer>
