<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="./index.html">Suma</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin">Admin Dashboard</a>
        </li>
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin/locations">Edit Locations</a>
        </li>
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin/initiatives">Edit Initiatives</a>
        </li>
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin/sessions">Sessions List</a>
        </li>
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin/jsonimport">Direct JSON Import</a>
        </li>
        <li class="">
          <a href="<?php echo $this->baseUrl(); ?>/admin/logout">Logout</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container" id="content-main">
  <header class="page-header">
    <h1>Suma Administrative Tools</h1>
  </header>
