<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container" id="header-container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/sumaserver/admin">Suma Admin</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="">
            <a href="/sumaserver/admin">Dashboard</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/locations">=Locations</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/initiatives">=Initiatives</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/sessions">Sessions</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/jsonimport">JSON Import</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container" id="content-main">
  <header class="page-header">
    <h1>Suma Administrative Tools</h1>
  </header>
