<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="./index.html">Suma</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="">
            <a href="/sumaserver/admin">Admin Dashboard</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/locations">Edit Locations</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/initiatives">Edit Initiatives</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/sessions">Sessions List</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/jsonimport">Direct JSON Import</a>
          </li>
          <li class="">
            <a href="/sumaserver/admin/logout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <header class="page-header">
    <h1>Suma Administrative Tools</h1>
  </header>
