<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Suma Admin Login</title>
  <?php echo $this->render('includes/head.php'); ?>
  <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
</head>
<body>
  <?php echo $this->render('admin/header_pre-login.phtml'); ?>
  <div class="container">
    <form name="login" method="post" action='authenticate' class="form-signin">
      <h2 class="form-signin-heading">Please sign in</h2>
      <input type='text' name='username' id="username" placeholder="Username">
      <input type='password' name='password' id='password' placeholder="Password">
      <button class="btn btn-large btn-primary" name='login' value='Login' type="submit">Sign in</button>
    </form>
  </div>
  <?php echo $this->render('admin/footer.phtml'); ?>
</body>
</html>
