<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Suma administrative tools</title>
  <?php echo $this->render('includes/head.php'); ?>
</head>
<body>
  <?php echo $this->render('admin/header.phtml'); ?>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <form name="login" method="post" action='authenticate' class="form-signin">
          <h2 class="form-signin-heading">Please sign in</h2>
          <input type='text' name='username' id="username" placeholder="Username">
          <input type='password' name='password' id='password' placeholder="Password">
          <button class="btn btn-large btn-primary" name='login' value='Login' type="submit">Sign in</button>
        </form>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
  <?php echo $this->render('admin/footer.phtml'); ?>
</body>
</html>
